name: iOS Build(Self Hosted)

on:
  workflow_dispatch:

jobs:
  build_unity:
    name: Build iOS
    runs-on: self-hosted
    env:
      IOS_APP_ID: com.DefaultCompan.CISample
      IOS_BUILD_PATH: ${{ format('{0}/build/iOS', github.workspace) }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_PERSONAL_ACCESS_TOKEN: ${{ secrets.MATCH_PERSONAL_ACCESS_TOKEN }}
      MATCH_REPOSITORY_ACCOUNT: ${{ secrets.MATCH_REPOSITORY_ACCOUNT }}
      APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      IPA_OUTPUT_PATH: ${{ format('{0}/Build.ipa', github.workspace) }}
      DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
      DEPLOYGATE_USER_NAME: ${{ secrets.DEPLOYGATE_USER_NAME }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Build iOS
        run: |
          UNITY_APP_PATH="/Applications/Unity/Hub/Editor/2022.3.38f1/Unity.app/Contents/MacOS/Unity"
          UNITY_PROJECT_PATH="./"
          UNITY_BUILDE_NAME="BuildScript.BuildForIOS"
          UNITY_LOG_PATH="./build/iOS/build.log"
          PROJECT_DIR="./build/iOS"

          $UNITY_APP_PATH -batchmode \
              -quit \
              -projectPath $UNITY_PROJECT_PATH \
              -executeMethod $UNITY_BUILDE_NAME \
              -logfile $UNITY_LOG_PATH \
              -output-dir $PROJECT_DIR

          if [ $? -eq 1 ]; then
              echo "error!! check logfile: ${UNITY_LOG_PATH}"
              exit 1
          fi

          echo "unity build success!!"

      - name: Cache Ruby Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            bundle-

      - name: Cache restore cocoapods
        uses: actions/cache@v2
        if: ${{ always() }}
        with:
          path: |
            build/iOS/iOS/Pods
            ~/.cocoapods/repos
          key: Pods-${{ hashFiles('**/Podfile') }}
          restore-keys: Pods-

      - name: Prepare for fastlane # GateKeeper対策
        run: |
          sudo spctl --master-disable

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Fetch UDID from DeployGate
        run: |
          curl -s -H "Authorization: token ${{ secrets.DEPLOYGATE_API_KEY }}" \
            https://deploygate.com/api/users/${{ secrets.DEPLOYGATE_USER_NAME }}/devices \
            | jq '.results[] | "\(.udid),\(.name)"' > devices.txt

      - name: Build XCode
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'ios build'
  
      - name: Upload to DeployGate
        run: |
          IPA_PATH=$(find . -name "*.ipa" | head -n 1)
          echo "Uploading $IPA_PATH to DeployGate"
          RESPONSE=$(curl -s -F "file=@$IPA_PATH" \
               -F "token=$DEPLOYGATE_API_KEY" \
               -F "message=New build from GitHub Actions" \
               https://deploygate.com/api/users/$DEPLOYGATE_USER_NAME/apps)
          APP_URL=$(echo $RESPONSE | jq -r '.results.revision_url')
          APP_URL=$(echo "$APP_URL" | sed "s|\*\*\*|$DEPLOYGATE_USER_NAME|")
          AUTHOR_NAME=${{ github.event.client_payload.name }}
          echo "DeployGate App URL: $APP_URL"
          echo $RESPONSE
          echo "DeployGate App URL: $APP_URL"
          
          MESSAGE="@here \nデプロイが完了しましたよ！\n$APP_URL"
          echo "Sending message to Discord: $MESSAGE"

          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_WEBHOOK_URL

      - name: Cleanup
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: Build-iOS